src/Core/Areas/Chain/Pages/Blocks/Details.cshtml.cs
using Data.Persistence;
using Domain;
using LiteDB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Core.Areas.Chain.Pages.Blocks
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ILedgerRepository _ledger;

        public DetailsModel(
            ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public Block Block { get; set; }

        public IActionResult OnGet(string id)
        {
            Block = _ledger.GetById(id);

            if (Block is null)
                return NotFound();

            return Page();
        }
    }
}

src/Core/Areas/Chain/Pages/Certifications/Details.cshtml.cs
using Data.Persistence;
using Domain;
using LiteDB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;

namespace Core.Areas.Chain.Pages.Certifications
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ILedgerRepository _ledger;
        
        public DetailsModel(
            ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public Certificate Certificate { get; set; }
        public Block Block { get; set; }
        
        public IActionResult OnGet(string hash)
        {
            Block = _ledger.GetByHash(hash);

            if (Block is null || Block.Type != typeof(Certificate).Name)
                return NotFound();

            Certificate = Block.Data.FromJson<Certificate>();
            return Page();
        }
    }
}

src/Core/Areas/Chain/Pages/Certifications/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Persistence;
using Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Core.Areas.Chain.Pages.Certifications
{
    public class IndexModel : PageModel
    {
        private readonly ILedgerRepository _ledger;

        public IndexModel(ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public IDictionary<string, Certificate> Certificate { get; set; }

        public void OnGet()
        {
            var blocks = _ledger.GetAll();
            var dict = blocks.Where(b => b.Type == typeof(Certificate).Name)
                             .Select(b =>
                                  new KeyValuePair<string, Certificate>(
                                      b.Hash,
                                      b.Data.FromJson<Certificate>()));
            Certificate = new Dictionary<string, Certificate>(dict);
        }
    }
}

src/Core/Areas/Chain/Pages/Employees/Details.cshtml.cs
using Data.Persistence;
using Domain;
using LiteDB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;

namespace Core.Areas.Chain.Pages.Employees
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly INodeRepository _repository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly OrganizationOptions _orgOptions;

        public DetailsModel(
            INodeRepository repository,
            UserManager<IdentityUser> userManager,
            IOptionsMonitor<OrganizationOptions> orgOptions)
        {
            _repository = repository;
            _userManager = userManager;
            _orgOptions = orgOptions.CurrentValue;
        }

        public LocalEmployee LocalEmployee { get; set; }
        public bool IsCorrectEmployee { get; set; }
        public bool IsAdmin { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            var objId = new ObjectId(id);
            LocalEmployee = _repository.SingleById<LocalEmployee>(objId);

            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            IsAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            if (!IsAdmin)
            {
                if (user.UserName == LocalEmployee.UserName)
                    IsCorrectEmployee = true;
            }

            if (!IsAdmin && !IsCorrectEmployee)
                return Unauthorized();
            return Page();
        }

        public bool Verify() =>
            LocalEmployee.Verify(
                _orgOptions.PublicKey,
                LocalEmployee.VerificationSignature);
    }
}

src/Core/Areas/Chain/Pages/Organizations/Details.cshtml.cs
using Data.Persistence;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Core.Areas.Chain.Pages.Organizations
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ILedgerRepository _ledger;

        public DetailsModel(
            ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public Organization Organization { get; set; }
        public Block Block { get; set; }

        public IActionResult OnGet(string hash)
        {
            Block = _ledger.GetByHash(hash);
            Organization = Block.Data.FromJson<Organization>();
            return Page();
        }
    }
}

src/Core/Areas/Chain/Pages/Projects/Create.cshtml.cs
using Data.Persistence;
using Domain;
using LiteDB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using System.ComponentModel.DataAnnotations;
using Domain.Local;

namespace Core.Areas.Chain.Pages.Projects
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ILedgerRepository _ledger;
        private readonly OrganizationOptions _orgOptions;

        public CreateModel(
            ILedgerRepository ledger,
            IOptionsMonitor<OrganizationOptions> orgOptionsMonitor)
        {
            _orgOptions = orgOptionsMonitor.CurrentValue;
            _ledger = ledger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var project = new Project
            {
                Id = ObjectId.NewObjectId().ToString(),
                Title = Input.Title,
                Organization = _orgOptions.PublicKey,
                TotalXp = Input.TotalXp,
                Description = Input.Description
            };

            var previousHash = _ledger.GetLastBlockHash();
            var block = new Block
            {
                Id = ObjectId.NewObjectId().ToString(),
                Data = project.ToJson(),
                Type = typeof(Project).Name,
                Originator = project.Organization,
                PreviousBlockHash = previousHash
            };
            block.Sign(_orgOptions.PrivateKey)
                 .SetHash();

            _ledger.Insert(block);

            return RedirectToPage("./Details", new { hash = block.Hash });
        }
    }

    public class InputModel
    {
        [Display(Name = "Project Title")]
        public string Title { get; set; }

        [Display(Name = "Total Experience Points")]
        public decimal TotalXp { get; set; }

        public string Description { get; set; }
    }
}

src/Core/Areas/Chain/Pages/Projects/Details.cshtml.cs
using Data.Persistence;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Core.Areas.Chain.Pages.Projects
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ILedgerRepository _ledger;

        public DetailsModel(
            ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public Project Project { get; set; }
        public Block Block { get; set; }

        public IActionResult OnGet(string hash)
        {
            Block = _ledger.GetByHash(hash);
            Project = Block.Data.FromJson<Project>();
            return Page();
        }
    }
}

src/Core/Areas/Chain/Pages/Resignations/Details.cshtml.cs
using Data.Persistence;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Core.Areas.Chain.Pages.Resignations
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ILedgerRepository _ledger;

        public DetailsModel(
            ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public Resignation Resignation { get; set; }
        public Block Block { get; set; }

        public IActionResult OnGet(string hash)
        {
            Block = _ledger.GetByHash(hash);

            if (Block is null || Block.Type != typeof(Resignation).Name)
                return NotFound();

            Resignation = Block.Data.FromJson<Resignation>();
            return Page();
        }
    }
}

src/Core/Areas/Chain/Pages/UnitsOfWork/Details.cshtml.cs
using Data.Persistence;
using Domain;
using LiteDB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;

namespace Core.Areas.Chain.Pages.UnitsOfWork
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ILedgerRepository _ledger;
        
        public DetailsModel(
            ILedgerRepository ledger)
        {
            _ledger = ledger;
        }

        public UnitOfWork UnitOfWork { get; set; }
        public Block Block { get; set; }
        
        public IActionResult OnGet(string hash)
        {
            Block = _ledger.GetByHash(hash);

            if (Block is null || Block.Type != typeof(UnitOfWork).Name)
                return NotFound();

            UnitOfWork = Block.Data.FromJson<UnitOfWork>();
            return Page();
        }
    }
}

src/Core/Areas/Local/Pages/Certifications/Create.cshtml.cs
using Data.Persistence;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using LiteDB;

namespace Core.Areas.Local.Pages.Certifications
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly INodeRepository _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public CreateModel(
            INodeRepository repository,
            UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            IEnumerable<LocalEmployee> localEmployees;
            var user = await _userManager.GetUserAsync(User);
            IsAdmin = await _userManager.IsInRoleAsync(user, "Admin");
            if (IsAdmin)
            {
                localEmployees = _repository.GetAll<LocalEmployee>().Where(e => e.IsDeployed);
            }
            else
            {
                localEmployees = new List<LocalEmployee> {
                    _repository.SingleOrDefault<LocalEmployee>(
                        e => e.UserName == User.Identity.Name && e.IsDeployed)
                };
            }

            Employees = new SelectList(
                localEmployees,
                nameof(LocalEmployee.PublicKey),
                nameof(LocalEmployee.Name));

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();

            var user = await _userManager.GetUserAsync(User);
            IsAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            var employee =
                _repository.SingleOrDefault<LocalEmployee>(
                    e => e.UserName == user.UserName);
            IsCorrectEmployee = employee?.PublicKey == Input.Receiver;

            if (!IsAdmin && !IsCorrectEmployee) return Unauthorized();

            var certificate = new LocalCertificate
            {
                Id = ObjectId.NewObjectId().ToString(),
                Title = Input.Title,
                ReceiverPublicKey = Input.Receiver,
                Description = Input.Description
            };
            _repository.Insert(certificate);
            return RedirectToPage("./Details", new { certificate.Id });
        }

        public bool IsAdmin { get; set; }
        public bool IsCorrectEmployee { get; set; }

        public SelectList Employees;

        [BindProperty]
        public InputModel Input { get; set; }
    }

    public class InputModel
    {
        public string Title { get; set; }
        public string Receiver { get; set; }
        public string Description { get; set; }
    }
}

src/Core/Areas/Local/Pages/Certifications/Details.cshtml.cs
using Data.Persistence;
using Domain;
using LiteDB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Domain.Local;
using Microsoft.Extensions.Options;

namespace Core.Areas.Local.Pages.Certifications
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly INodeRepository _repository;
        private readonly ILedgerRepository _ledger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly OrganizationOptions _orgOptions;

        public DetailsModel(
            INodeRepository repository,
            ILedgerRepository ledger,
            UserManager<IdentityUser> userManager,
            IOptionsMonitor<OrganizationOptions> orgOptions)
        {
            _repository = repository;
            _userManager = userManager;
            _ledger = ledger;
            _orgOptions = orgOptions.CurrentValue;
        }

        public LocalEmployee LocalEmployee { get; set; }
        public LocalCertificate Certificate { get; set; }
        public bool IsCorrectEmployee { get; set; }
        public bool IsAdmin { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            var objId = id;
            Certificate = _repository.SingleById<LocalCertificate>(objId);
            LocalEmployee =
                _repository.SingleOrDefault<LocalEmployee>(
                    e => e.PublicKey == Certificate.ReceiverPublicKey);
            
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            IsAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            if (!IsAdmin)
            {
                if (user.UserName == LocalEmployee.UserName)
                {
                    IsCorrectEmployee = true;
                }
            }

            if (!IsAdmin && !IsCorrectEmployee)
                return Unauthorized();

            return Page();
        }

        public async Task<IActionResult> OnPostDeployAsync(string id)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            IsAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            if (!IsAdmin)
                return Unauthorized();

            Certificate = _repository.SingleById<LocalCertificate>(id);

            var certificate = new Certificate
            {
                Id = Certificate.Id,
                Issuer = _orgOptions.PublicKey,
                Owner = Certificate.ReceiverPublicKey,
                Title = Certificate.Title,
                Description = Certificate.Description,
                OwnerSignature = Certificate.ReceiverSignature
            };

            var prevHash = _ledger.GetLastBlockHash();

            var block = new Block
            {
                Id = ObjectId.NewObjectId().ToString(),
                PreviousBlockHash = prevHash,
                Originator = _orgOptions.PublicKey,
                Data = certificate.ToJson(),
                Type = typeof(Certificate).Name
            };
            block.Sign(_orgOptions.PrivateKey);
            block.SetHash();

            await _ledger.Insert(block);
            Certificate.IsDeployed = true;
            _repository.Update(Certificate);
            return RedirectToPage("/Certifications/Details",
                new { hash = block.Hash, area = "Chain" });
        }
    }
}

src/Core/Areas/Local/Pages/Certifications/Index.cshtml.cs
using Data.Persistence;
using Domain;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace Core.Areas.Local.Pages.Certifications
{
    public class IndexModel : PageModel
    {
        private readonly INodeRepository _repository;
        public IndexModel(INodeRepository repository)
        {
            _repository = repository;
        }

        public IEnumerable<LocalCertificate> LocalCertificates { get; set; }

        public void OnGet()
        {
            LocalCertificates = _repository.GetAll<LocalCertificate>();
        }
    }
}

src/Core/Areas/Local/Pages/Certifications/Create.cshtml
@page
@model Core.Areas.Local.Pages.Certifications.CreateModel
@{
    ViewData["Title"] = "New Local Certificate";
}


<div class="card input-card">
    <div class="card-body">
        <div class="card-title">
            <h1 class="display-4">New Local Certificate</h1>
        </div>
        <div class="card-text">
            <form method="post">
                <div class="form-group row">
                    <label asp-for="Input.Title"
                           class="col-sm-3 col-form-label">
                    </label>

                    <div class="col-sm-9">
                        <input asp-for="Input.Title"
                                class="form-control">
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Input.Receiver"
                           class="col-sm-3 col-form-label">
                    </label>

                    <div class="col-sm-9">
                        <select asp-for="Input.Receiver"
                                asp-items="Model.Employees"
                                class="form-control">
                            <option selected disabled>
                                Select an Employee
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Input.Description"
                           class="col-sm-3 col-form-label">
                    </label>

                    <div class="col-sm-9">
                        <textarea asp-for="Input.Description"
                                  class="form-control">
                        </textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                    </label>

                    <div class="col-sm-9">
                        <input type="submit"
                               class="btn btn-primary" value="Save">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/Core/Areas/Local/Pages/Certifications/Details.cshtml
@page "{handler?}"
@model Core.Areas.Local.Pages.Certifications.DetailsModel
@{
    ViewData["Title"] = "Local Certificate";
}

<div class="card details-card mb-2">
    <div class="card-header">
        Local Certificate
    </div>
    <div class="card-body">
        <div class="card-title">
            <h1 class="display-4">
                @Model.Certificate.Title
            </h1>
        </div>

        <div class="card-text">
            <table class="table table-sm table-striped table-hover">
                <tbody>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Certificate.Id)</th>
                        <td class="text-right">
                            <code>
                                @Model.Certificate.Id
                            </code>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            Receiver's Name
                        </th>
                        <td class="text-right">
                            @Model.LocalEmployee.Name
                        </td>
                    </tr>


                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Certificate.ReceiverPublicKey)</th>
                        <td class="text-right">
                            <code>
                                @Model.Certificate.ReceiverPublicKey
                            </code>
                        </td>
                    </tr>

                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Certificate.Description)</th>
                        <td class="text-right">
                                @Model.Certificate.Description
                        </td>
                    </tr>

                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Certificate.ReceiverSignature)</th>
                        <td class="text-right">
                            <code>
                                @Model.Certificate.ReceiverSignature
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Certificate.IsDeployed)</th>
                        <td class="text-right">@(Model.Certificate.IsDeployed ? "Yes" : "No")</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer">
        @{
            var api =
                Url.ActionLink(
                    "Delete",
                    "Certifications",
                    new { Model.Certificate.Id, area = "" });

            var returnUrl = Url.Page("./Index");
        }
        @api
        <div class="row">
            <div class="col-6">
                @if (Model.IsAdmin)
                {
                    <a href="#"
                       class="btn btn-danger text-white js-remove-item"
                       data-href="@api"
                       data-returnUrl="@returnUrl">
                        Delete
                    </a>
                }
            </div>

            <div class="col-6 text-right">
                @if (Model.IsCorrectEmployee
                 && string.IsNullOrWhiteSpace(Model.Certificate.ReceiverSignature))
                {
                    <a asp-page="./Verification"
                       asp-route-id="@Model.Certificate.Id.ToString()"
                       class="btn btn-primary text-white">
                        Verify
                    </a>
                }

                @if (Model.IsAdmin && !Model.Certificate.IsDeployed)
                {
                    if (Model.Certificate.IsReadyToDeploy)
                    {
                        <form method="post"
                              asp-page-handler="deploy"
                              asp-route-id="@Model.Certificate.Id">
                            <button class="btn btn-primary">
                                Deploy
                            </button>
                        </form>
                    }
                    else
                    {
                        <span class="text-info">Pending Verification</span>
                    }
                }
            </div>
        </div>
    </div>
</div>

<a asp-page="./Index"
   class="btn btn-secondary">
    Back to Index
</a>

src/Core/Areas/Local/Pages/Certifications/Index.cshtml
@page 
@using Domain
@model Core.Areas.Local.Pages.Certifications.IndexModel
@{
    ViewData["Title"] = "Index";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="display-4">
                        Local Certificates
                    </h1>
                </div>
                <div class="col-md-6 text-right">
                    <a  asp-page="./Create"
                        class="btn btn-primary text-white">Add New</a>
                </div>
            </div>
        </div>  
        <div class="card-text">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Receiver</th>
                        <th>Description</th>
                        <td></td>
                    </tr>
                </thead>  
                <tbody>
                @foreach (var certificate in Model.LocalCertificates)
                {
                    var tblClass = certificate.IsDeployed ? "table-success" : "table-warning";
                    <tr class="@tblClass">
                        @*<td>@emp.Id</td>*@
                        <td>@certificate.Id</td>
                        <td>@certificate.Title</td>
                        <td><code>@certificate.ReceiverPublicKey.GetLast(30)</code></td>
                        <td>@certificate.Description</td>
                        <td class="text-right">
                            <a asp-page="./Details"
                               asp-route-id="@certificate.Id.ToString()"
                               class="btn btn-sm btn-success">
                                View
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/Core/Areas/Local/Pages/Certifications/Verification.cshtml
@page
@model Core.Areas.Local.Pages.Certifications.VerificationModel
@{
    ViewData["Title"] = "Unit of Work Confirmation";
}

<div class="card details-card mb-2">
    <div class="card-header">
        Confirm Unit of Work
    </div>
    <div class="card-body">
        <div class="card-title">
            <h1 class="display-4">
                @Model.Certificate.Title
            </h1>
        </div>

        <div class="card-text">
            <form method="post">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"
                           asp-for="Certificate.Id">
                    </label>

                    <div class="col-sm-9">
                        <code>
                            @Model.Certificate.Id
                        </code>
                    </div>
                </div>
                         
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                        Receiver's Name
                    </label>

                    <div class="col-sm-9">
                            @Model.LocalEmployee.Name
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"
                           asp-for="Certificate.ReceiverPublicKey">
                    </label>

                    <div class="col-sm-9">
                        <code>
                            @Model.Certificate.ReceiverPublicKey
                        </code>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                        Verification Message
                    </label>

                    <div class="col-sm-9">
                        <code>
                            @Model.VerificationPayload
                        </code>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Input.VerificationSignature"
                           class="col-sm-3 col-form-label">
                    </label>

                    <div class="col-sm-9">
                        <textarea asp-for="Input.VerificationSignature"
                                  class="form-control">
                        </textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                    </label>

                    <div class="col-sm-9">
                        <input type="submit"
                               class="btn btn-primary" value="Submit">
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>